onramp:
  - id: input
    type: blaster
    codec: string
    config:
      source: /test_data     
offramp:
  - id: stdout-output
    type: blackhole
    config:
      warmup_secs: 10
      stop_after_secs: 40
      significant_figures: 1
